### ISSUE TITLE
Can't get this to deploy, fails on VPCStack step

### ISSUE THREAD

**Issue by flybd5** [aws-quickstart/quickstart-eks-rancher#19]
amazon-eks-entrypoint-new-vpc.template

Every time I try to create this stack it fails. I have tried doing it as vanilla as I can and it still always fails. ??

Embedded stack arn:aws:cloudformation:us-east-1:717896939665:stack/ccRancher-VPCStack-1IAIFAGFWS43H/fe225400-8900-11eb-beb7-0e72af45bdc7 was not successfully created: The following resource(s) failed to create: [PrivateSubnet3ARouteTableAssociation, NAT1EIP, NAT2EIP, PublicSubnet1RouteTableAssociation, NAT3EIP, PublicSubnet3RouteTableAssociation, PrivateSubnet2ARouteTableAssociation, PublicSubnetRoute, PrivateSubnet1ARouteTableAssociation, PublicSubnet2RouteTableAssociation].

**Comment by brisbane** [comment]
IIRC I saw the first error and it was because I had not created the shared resources (the autodetect does not work)
https://github.com/aws-quickstart/quickstart-amazon-eks/issues/259

For the second, have you tried looking at the stack events from the console or with
aws cloudformation   describe-stack-events --stack-name arn:aws:cloudformation:eu-north-xxx:stack/RancherEKS-EKSStack-MTZBxxx 

Ive had similar issues and ended up on this page, and these debuggings helped me to see the issue I had.  Check your quotas...
